# Generated by Django 2.1.2 on 2018-12-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181215_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
