# Generated by Django 2.1.2 on 2018-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
