# Generated by Django 2.1.2 on 2018-12-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_post_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bids',
        ),
    ]
